### ISSUE TITLE
Installed in a different location error

### ISSUE THREAD

**Issue by buhguhjuh** [teamclouday/AndroidMic#35]
Hello. Whenever I try to launch the app, i get this error. It happens both thru .application and thru .exe
![image](https://github.com/user-attachments/assets/259aa092-6b48-4577-a5be-0cd3be0d62a9)

The details.txt say that it is installed in a rar folder in appdata, but the catch is that the temp folder in appdata does not exist. 
![image](https://github.com/user-attachments/assets/4e604920-8f57-4dac-a1cb-3571015af5d3)

I tried deleting temp files thru disc cleanup, restarting pc, looked at add or remove programs, pasting the pathway to the folder directly into file explorer, nothing has worked. There is no way to uninstall the program as well, how it says to do in the details. The app only shows the error

Details are here (sorry for the lack of formatting, its my first time using github)

PLATFORM VERSION INFO
	Windows 			: 10.0.19043.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.4270.0 built by: NET48REL1LAST_C
	clr.dll 			: 4.8.4515.0 built by: NET48REL1LAST_C
	dfdll.dll 			: 4.8.4270.0 built by: NET48REL1LAST_C
	dfshim.dll 			: 10.0.19041.30000 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///C:/Users/.../Desktop/android%20mic/release/Windows/AndroidMic.application

IDENTITIES
	Deployment Identity		: AndroidMic.application, Version=2.0.0.0, Culture=en, PublicKeyToken=0000000000000000, processorArchitecture=msil

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\...\Desktop\android mic\release\Windows\AndroidMic.application resulted in exception. Following failure messages were detected:
		+ You cannot start application AndroidMic from this location because it is already installed from a different location.
		+ You cannot start application AndroidMic from location file:///C:/Users/.../Desktop/android%20mic/release/Windows/AndroidMic.application it is already installed from location file:///C:/Users/.../AppData/Local/Temp/Rar$EXa41704.41336/release/Windows/AndroidMic.application. You can start it from location file:///C:/Users/.../AppData/Local/Temp/Rar$EXa41704.41336/release/Windows/AndroidMic.application or you can uninstall it and reinstall it from location file:///C:/Users/.../Desktop/android%20mic/release/Windows/AndroidMic.application. If you reinstall the application, be aware that you might lose any customizations that you made to the application.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	* The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
	* [2024-09-04 14:59:21] : Activation of C:\Users\...\Desktop\android mic\release\Windows\AndroidMic.application has started.
	* [2024-09-04 14:59:21] : Processing of deployment manifest has successfully completed.

ERROR DETAILS
	Following errors were detected during this operation.
	* [2024-09-04 14:59:21] System.Deployment.Application.DeploymentException (DeploymentUriDifferent)
		- You cannot start application AndroidMic from this location because it is already installed from a different location.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ApplicationActivator.CheckDeploymentProviderValidity(ActivationDescription actDesc, SubscriptionState subState)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Deployment.Application.DeploymentException (DeploymentUriDifferent)
		- You cannot start application AndroidMic from location file:///C:/Users/.../Desktop/android%20mic/release/Windows/AndroidMic.application it is already installed from location file:///C:/Users/.../AppData/Local/Temp/Rar$EXa41704.41336/release/Windows/AndroidMic.application. You can start it from location file:///C:/Users/.../AppData/Local/Temp/Rar$EXa41704.41336/release/Windows/AndroidMic.application or you can uninstall it and reinstall it from location file:///C:/Users/.../Desktop/android%20mic/release/Windows/AndroidMic.application. If you reinstall the application, be aware that you might lose any customizations that you made to the application.
		- Source: 
		- Stack trace:

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by teamclouday** [comment]
Sorry just saw the issue. Try to look for `C:/Users/YOUR_NAME/AppData/Local/Apps` folder. There should be subfolder somewhere starts with `andr...` (Try to click a few times because they're located deep in the folder tree). Delete those folders and the app will be deleted. I haven't tried it but hope it helps.
